
spring:
  profiles:
    active: company

# 解决swagger3无法访问页面
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
logging:
  level:
    org.springframework.security.web: debug

mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl