
#minio:
#  access-key: root
#  secret-key: 1234qwer
#  endpoint: http://192.190.10.182:9800
#  bucket: test

debug: true
#secure:
#  field:
#    enabled: false
#    private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBANfwsEoQtSzLxWKAaj04cBAi8TEgJ73L/tdv78XJnjpnfF8ezEyz21Ye1sbqiTJ89yMvotnYkDgQCDadQtxmmdsexE1kJor06QAThL5jjZuty4KapiG1+k2ggbB6pliUEYNDp+s6yxbPiXus66A3yPNuaaKMKHM9vhyAS77oQchVAgMBAAECgYARDIpGo4oPMHZAzPjv8dt7LEV7U1mzG2Ur/XgvVzgWAWMPuYVEzkB6sxjSMxgQ84F2dp9DcHZ2geGI7YkNXYM3ftRr1rh2/rgHn8dVEIPRKuHp8pGr2aMg2tMggCYYUCwTS8MjkqPg7d9qXZBbhGsNTrSZ1FdBbuNHcO3BiYlB0wJBAO/y6VxMF9OHzLyvlOk9rjh+cm4W+rNO0t56SbXxX6bwohAFdddLdkNYV00dfRsAsgRyeivZGt/YP/YVn3MIGXcCQQDmYqHInmfe4PQZdfHXKdUch0d+REaJIUF/Xytazib4OKtDChuIXW+wMB76Pb/YrlgTYh8fTNaL4nOCJuu6GF+TAkEAri9hdk4K0dT4LFUtvW+4RGyOdxqZXYcwDq8pSTnynQZ8LzM3i1XNgS/lGCb7BZoooI/V3nTZTHv4WpTxzhioGwJAJIgPT1iO7/CLxF3Hc27WtCdfVs5MwQHc+O2GWmfGFiYmQgMgSodGZpG618Ni4GEE5k3w0W3Ft3i5CDJTvraOsQJBAN8VoRXDwhYNuGmFWfWil/3uYyzmWB6P4DU4v6YWn5EWkpU/laVL5yItPPMSkB2w9EFL9GAduJJPz4R7aRdAEew=
#    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDX8LBKELUsy8VigGo9OHAQIvExICe9y/7Xb+/FyZ46Z3xfHsxMs9tWHtbG6okyfPcjL6LZ2JA4EAg2nULcZpnbHsRNZCaK9OkAE4S+Y42brcuCmqYhtfpNoIGweqZYlBGDQ6frOssWz4l7rOugN8jzbmmijChzPb4cgEu+6EHIVQIDAQAB
